# Generated by Django 3.2.6 on 2021-11-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=7000)),
                ('option1', models.CharField(max_length=700)),
                ('option2', models.CharField(max_length=700)),
                ('option3', models.CharField(max_length=700)),
                ('option4', models.CharField(max_length=700)),
            ],
        ),
    ]
