# Generated by Django 3.2.6 on 2021-11-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='id',
        ),
        migrations.AddField(
            model_name='question',
            name='q_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=models.CharField(default='', max_length=700),
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.CharField(default='', max_length=700),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.CharField(default='', max_length=700),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.CharField(default='', max_length=700),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(default='', max_length=7000),
        ),
    ]
