# Generated by Django 3.2.6 on 2021-12-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0002_auto_20211113_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(default='', max_length=700),
        ),
    ]
