# Generated by Django 3.2.6 on 2021-12-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0004_rename_answer_question_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user_ans',
            field=models.CharField(default='', max_length=700),
        ),
    ]
