# Generated by Django 3.2.6 on 2022-09-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0005_question_user_ans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_s1',
            fields=[
                ('q_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('question', models.CharField(default='', max_length=7000)),
                ('option1', models.CharField(default='', max_length=700)),
                ('option2', models.CharField(default='', max_length=700)),
                ('option3', models.CharField(default='', max_length=700)),
                ('option4', models.CharField(default='', max_length=700)),
                ('ans', models.CharField(default='', max_length=700)),
                ('user_ans', models.CharField(default='', max_length=700)),
            ],
        ),
    ]
